a=int(input("Enter the value:"))
b=int(input("Enter the value:"))
c=int(input("Enter the value:"))
d=int(input("Enter the value:"))
print(a+b)
print(a-b)
print(c*d)
print(d//a)
print(c%d)
print(b**5)
print(d/c)


e=int(input("Enter the value:"))
f=int(input("Enter the value:"))
g=int(input("Enter the value:"))
h=int(input("Enter the value:"))
print(e==h)
print(h!=g)
print(f>e)
print(e<h)
print(e>=h)
print(g<=f)

