from tkinter import *
root=Tk()
root.title("FORM")
root.geometry("2000x2000")
l=Label(root,text="DATA")
l.pack()
l1=Label(root,text="Username :")
l1.place(x=450,y=120)
e1=Entry(root)
e1.place(x=550,y=120)
l2=Label(root,text="Registerid :")
l2.place(x=450,y=180)
e2=Entry(root)
e2.place(x=550,y=180)
l3=Label(root,text="Password :")
l3.place(x=450,y=240)
e3=Entry(root)
e3.place(x=550,y=240)
l4=Label(root,text="Aadharno :")
l4.place(x=450,y=300)
e4=Entry(root)
e4.place(x=550,y=300)
def save():
    a=e1.get()
    x=e2.get()
    y=e3.get()
    z=e4.get()
    print("Username :",a)
    print("Registerid :",x)
    print("Password :",y)
    print("Aadharno :",z)
    #open("sri.txt","x")
    moon=open("sri.txt","w")
    moon.write("Username :" + a +"\n")
    moon.write("Registerid :" + x + "\n" )
    moon.write("Password :" + y + "\n")
    moon.write("Aadharno :" + z + "\n")
    moon.close()
b=Button(root,text="Click",command=save)
b.place(x=550,y=450)
root.mainloop()

